name: bloc_common
description:
version: 0.0.2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: any
  
  logger: any
  
  foundation:
    git:
      url: https://github.com/pshonkaaa/package.foundation.dart.git